// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPWaZxaRWox0MTdEq9mn0BHrtiJGCNh84',
    appId: '1:148932604061:web:028e722b82d5b5ebcbe474',
    messagingSenderId: '148932604061',
    projectId: 'authflutter-e1097',
    authDomain: 'authflutter-e1097.firebaseapp.com',
    storageBucket: 'authflutter-e1097.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsl1eY4Y4SxAtHUTpDYk7nEjSq2Gc96Ok',
    appId: '1:148932604061:android:01a8d70a2d9c9956cbe474',
    messagingSenderId: '148932604061',
    projectId: 'authflutter-e1097',
    storageBucket: 'authflutter-e1097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLaqnTTGlrfe7InAj1-mI094e-o9ONYw',
    appId: '1:148932604061:ios:9849f159218b788ccbe474',
    messagingSenderId: '148932604061',
    projectId: 'authflutter-e1097',
    storageBucket: 'authflutter-e1097.appspot.com',
    iosClientId: '148932604061-4tl4v8oeo1ilko5nh8jqefjgdjo7q4nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailoginlogout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLaqnTTGlrfe7InAj1-mI094e-o9ONYw',
    appId: '1:148932604061:ios:08add159c4106638cbe474',
    messagingSenderId: '148932604061',
    projectId: 'authflutter-e1097',
    storageBucket: 'authflutter-e1097.appspot.com',
    iosClientId: '148932604061-vp6ourokkhp5vvbh92cc9ia700b3jfuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailoginlogout.RunnerTests',
  );
}
